name: build

on: workflow_dispatch

env:
  URLPERL: https://www.cpan.org/src/5.0/perl-5.30.0.tar.gz
  URLBIBER: https://github.com/plk/biber/archive/v2.15.tar.gz
  URLTESTPARFILES: https://master.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/testfiles
  BIBERTESTPARFILES: test.bib test.bcf test-dev.bcf unifont.ttf
  PERLPLATFORM: x86_64-linux
  PERLVERSION: 5.30.0
  MAKEFLAGS: -j1
  PARLIBSSYSROOT: /usr/lib/x86_64-linux-gnu
  PARLIBSSYS: libxml2.so libz.so libxslt.so libexslt.so libssl.so.1.1 libcrypto.so.1.1
  PARLIBS: /usr/lib/libbtparse.so
  PARMODULESSYS: "deprecate Pod::Simple::TranscodeSmart Pod::Simple::TranscodeDumb List::MoreUtils::XS List::SomeUtils::XS List::MoreUtils::PP HTTP::Status HTTP::Date Encode:: File::Find::Rule IO::Socket::SSL IO::String PerlIO::utf8_strict Text::CSV_XS DateTime"
  PARMODULESBIBER: "Biber::Input::file::bibtex Biber::Input::file::biblatexml Biber::Output::dot Biber::Output::bbl Biber::Output::bblxml Biber::Output::bibtex Biber::Output::biblatexml"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
       - name: Install Package Dependencies
         run: sudo apt-get install -y libxml2-dev libxslt-dev libbtparse-dev

       - name: Install Perl from source
         run: |
           mkdir perl 
           wget $URLPERL
           tar -xf $(basename $URLPERL) --strip-components=1 --directory=perl

           cd perl
           bash ./Configure -sde -Dprefix=$PWD/../prefix -Dhintfile=$PWD/../../../hintfile_native.sh -Aldflags=-lm -Accflags=-lm 
           #export MAKEFLAGS
           make
           make install
       
       - name: Install Biber Dependencies Without Test from Build.PL
         run: ./prefix/bin/cpan -T PAR PAR::Packer    Test::More Test::Differences File::Which    Module::Build    Config::AutoConf ExtUtils::LibBuilder    autovivification Class::Accessor Data::Dump Data::Compare Data::Uniqid DateTime::Format::Builder DateTime::Calendar::Julian File::Slurper IPC::Cmd IPC::Run3 List::AllUtils List::MoreUtils List::MoreUtils::XS Mozilla::CA Regexp::Common Log::Log4perl Unicode::Collate Unicode::Normalize Unicode::LineBreak Unicode::GCString Encode::Locale Encode::EUCJPASCII Encode::JIS2K Encode::HanExtra Parse::RecDescent PerlIO::utf8_strict XML::LibXML XML::LibXML::Simple XML::LibXSLT XML::Writer Sort::Key Storable Text::CSV Text::CSV_XS Text::Roman IO::String URI Text::BibTeX LWP::UserAgent LWP::Protocol::https Business::ISBN Business::ISSN Business::ISMN Lingua::Translit 

       - name: Download and Compile Biber
         run: |
           mkdir biber
           wget $URLBIBER
           tar -xf $(basename $URLBIBER) --strip-components=1 --directory biber
           
           # https://github.com/plk/biber/blob/dev/dist/linux_x86_64/build.sh
           # https://github.com/plk/biber/blob/dev/dist/linux_x86_64-musl/build.sh
           
           ROOT=$PWD
           PREFIX=$ROOT/prefix
           PARFILESBIBER="../data/biber-tool.conf;lib/Biber/biber-tool.conf ../data/schemata/config.rnc;lib/Biber/config.rnc ../data/schemata/config.rng;lib/Biber/config.rng ../data/schemata/bcf.rnc;lib/Biber/bcf.rnc ../data/schemata/bcf.rng;lib/Biber/bcf.rng ../data/bcf.xsl;Biber/bcf.xsl Biber/LaTeX/recode_data.xml;Biber/LaTeX/recode_data.xml"
           PARFILESUNICODE="$PREFIX/lib/$PERLVERSION/Unicode/Collate/Locale;lib/Unicode/Collate/Locale $PREFIX/lib/$PERLVERSION/Unicode/Collate/CJK;lib/Unicode/Collate/CJK $PREFIX/lib/$PERLVERSION/Unicode/Collate/allkeys.txt;lib/Unicode/Collate/allkeys.txt $PREFIX/lib/$PERLVERSION/Unicode/Collate/keys.txt;lib/Unicode/Collate/keys.txt"
           PARFILESSYS="$PREFIX/lib/site_perl/$PERLVERSION/Mozilla/CA/cacert.pem;lib/Mozilla/CA/cacert.pem $PREFIX/lib/$PERLVERSION/$PERLPLATFORM/PerlIO;lib/PerlIO $PREFIX/lib/$PERLVERSION/$PERLPLATFORM/auto/PerlIO;lib/auto/PerlIO $PREFIX/lib/site_perl/$PERLVERSION/Business/ISBN/RangeMessage.xml;lib/Business/ISBN/RangeMessage.xml"
           
           cd biber/lib
           PAR_VERBATIM=1 $PREFIX/bin/pp $(printf -- "--module %s " $PARMODULESSYS) $(printf -- "--module %s " $PARMODULESBIBER) $(printf -- "--link $PARLIBSSYSROOT/%s " $PARLIBSSYS) $(printf -- "--link %s " $PARLIBS) $(printf -- "--addfile %s " $PARFILESBIBER) $(printf -- "--addfile %s " $PARFILESUNICODE) $(printf -- "--addfile %s " $PARFILESSYS) --unicode --cachedeps=scancache --output=$ROOT/biber.par ../bin/biber



           #           cd biber
           #           ../prefix/bin/perl ./Build.PL
           #           ../prefix/bin/perl ./Build install
           #       
           #       - name: Test Biber
           #         run: |
           #           cd biber
           #           wget $(printf "$URLTESTPARFILES/%s " $BIBERTESTPARFILES)
           #           ../prefix/bin/perl ./Build test || true
           #           ../prefix/bin/perl ./bin/biber --validate-control --convert-control test || true
