name: Biber CI

env:
  URLPERL: https://www.cpan.org/src/5.0/perl-5.32.0.tar.gz
  URLBIBER: https://github.com/plk/biber/archive/v2.19.tar.gz
  MAKEFLAGS: -j2
  BIBER_DEV_TESTS: 1
  
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
       - name: Install Perl
         run: |
           mkdir perlsource
           wget -nc $URLPERL
           tar -xf $(basename $URLPERL) --strip-components=1 --directory=perlsource

           pushd perlsource
           bash +x ./Configure -sde -Dprefix="$RUNNER_WORKSPACE/localperl"
           test -f Makefile
           make
           make install
           popd

       - name: Set ENV
         run: |
           echo "$RUNNER_WORKSPACE/localperl/bin" >> $GITHUB_PATH
           echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RUNNER_WORKSPACE/localperl/lib" >> $GITHUB_ENV

       - name: Install Biber
         run: |
           mkdir biber
           wget $URLBIBER
           tar -xf $(basename $URLBIBER) --strip-components=1 --directory biber

       - name: Install Biber Dependencies Without Test
         run: |
           cd biber
           cpan -T Module::Build
           perl Build.PL
           perl ./Build installdeps --cpan_client "cpan -T"
           perl ./Build test

#name: buildbiberdeps
#on: workflow_dispatch
#jobs:
#  buildbiberdeps:
#    runs-on: ubuntu-22.04
#    steps:
#       - name: Install Package Dependencies
#         run: sudo apt-get install -y libxml2-dev libxslt-dev libbtparse-dev
#       - name: Install Biber Dependencies Without Test from Build.PL
#         run: |
#          cpan -T Test::More Test::Differences File::Which    Module::Build    Config::AutoConf ExtUtils::LibBuilder    autovivification Class::Accessor Data::Dump Data::Compare Data::Uniqid DateTime::Format::Builder DateTime::Calendar::Julian File::Slurper IPC::Cmd IPC::Run3 List::AllUtils List::MoreUtils List::MoreUtils::XS Mozilla::CA Regexp::Common Log::Log4perl Unicode::Collate Unicode::Normalize Unicode::LineBreak Unicode::GCString Encode::Locale Encode::EUCJPASCII Encode::JIS2K Encode::HanExtra Parse::RecDescent PerlIO::utf8_strict XML::LibXML XML::LibXML::Simple XML::LibXSLT XML::Writer Sort::Key Storable Text::CSV Text::CSV_XS Text::Roman IO::String URI Text::BibTeX LWP::UserAgent LWP::Protocol::https Business::ISBN Business::ISSN Business::ISMN Lingua::Translit 
#          cpan -T PAR PAR::Packer
#          which pp
