name: build

on: workflow_dispatch

env:
  URLPERL: https://www.cpan.org/src/5.0/perl-5.32.0.tar.gz
  URLBIBER: https://github.com/plk/biber/archive/v2.15.tar.gz
  URLTESTFILES: https://master.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/testfiles
  BIBERTESTFILES: test.bib test.bcf test-dev.bcf unifont.ttf
  MAKEFLAGS: -j2

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
       - name: Install Package Dependencies
         run: sudo apt-get install -y libxml2-dev libxslt-dev libbtparse-dev

       - name: Install Perl from source
         run: |
           mkdir perl 
           wget -nc $URLPERL
           tar -xf $(basename $URLPERL) --strip-components=1 --directory=perl

           cd perl
           bash +x ./Configure -sde -Dprefix="$PWD/../prefix"
           test -f Makefile
           export MAKEFLAGS
           make
           make install
       
       - name: Install Biber Dependencies Without Test from Build.PL
         run: ./prefix/bin/cpan -T Test::More Test::Differences File::Which    Module::Build    Config::AutoConf ExtUtils::LibBuilder    autovivification Class::Accessor Data::Dump Data::Compare Data::Uniqid DateTime::Format::Builder DateTime::Calendar::Julian File::Slurper IPC::Cmd IPC::Run3 List::AllUtils List::MoreUtils List::MoreUtils::XS Mozilla::CA Regexp::Common Log::Log4perl Unicode::Collate Unicode::Normalize Unicode::LineBreak Unicode::GCString Encode::Locale Encode::EUCJPASCII Encode::JIS2K Encode::HanExtra Parse::RecDescent PerlIO::utf8_strict XML::LibXML XML::LibXML::Simple XML::LibXSLT XML::Writer Sort::Key Storable Text::CSV Text::CSV_XS Text::Roman IO::String URI Text::BibTeX LWP::UserAgent LWP::Protocol::https Business::ISBN Business::ISSN Business::ISMN Lingua::Translit 

       - name: Download and Compile Biber
         run: |
           mkdir biber
           wget $URLBIBER
           tar -xf $(basename $URLBIBER) --strip-components=1 --directory biber

           cd biber
           ../prefix/bin/perl ./Build.PL
           ../prefix/bin/perl ./Build install
       
       - name: Test Biber
         run: |
           cd biber
           wget $(printf "$URLTESTFILES/%s " $BIBERTESTFILES)
           ../prefix/bin/perl ./Build test || true
           ../prefix/bin/perl ./bin/biber --validate-control --convert-control test || true
