name: buildbiberdeps

env:
  URLPERL: https://www.cpan.org/src/5.0/perl-5.32.0.tar.gz
  URLBIBER: https://github.com/plk/biber/archive/v2.19.tar.gz
  MAKEFLAGS: -j2
  BIBER_DEV_TESTS: 0
  
on: workflow_dispatch

jobs:
  buildbiberdeps:
    runs-on: ubuntu-22.04
    steps:
       - name: Install Package Dependencies
         run: sudo apt install -y libxml2-dev libxslt-dev libbtparse-dev p7zip-full

       - name: Install Biber
         run: mkdir biber && wget $URLBIBER && tar -xf $(basename $URLBIBER) --strip-components=1 --directory biber

       - name: Install Perl
         run: |
           mkdir perlsource
           wget -nc $URLPERL
           tar -xf $(basename $URLPERL) --strip-components=1 --directory=perlsource

           pushd perlsource
           bash +x ./Configure -sde -Dprefix="$RUNNER_WORKSPACE/localperl"
           test -f Makefile
           make
           make install
           popd
           sudo rm -rf /usr/local/perl && sudo ln -s $RUNNER_WORKSPACE/localperl /usr/local/perl
           #echo "$RUNNER_WORKSPACE/localperl/bin" >> $GITHUB_PATH
           echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RUNNER_WORKSPACE/localperl/lib" >> $GITHUB_ENV

       - name: Install Biber Dependencies Without Test
         run: |
           # /home/runner/work/busyperl/localperl/bin
           cd biber
           echo 'echo MYCPAN:$@; $RUNNER_WORKSPACE/localperl/bin/cpan -T $@' > ./mycpan.sh; chmod +x ./mycpan.sh; cat ./mycpan.sh
           ./mycpan.sh Module::Build
           ./mycpan.sh Config::AutoConf ExtUtils::LibBuilder Business::ISBN Business::ISMN Business::ISSN    Class::Accessor Data::Compare Data::Dump Data::Uniqid DateTime::Calendar::Julian DateTime::Format::Builder    Encode::EUCJPASCII Encode::HanExtra Encode::JIS2K Encode::Locale File::Slurper IO::String IPC::Run3 LWP::Protocol::https LWP::UserAgent    Lingua::Translit List::AllUtils List::MoreUtils List::MoreUtils::XS Log::Log4perl Mozilla::CA    Parse::RecDescent PerlIO::utf8_strict Regexp::Common Sort::Key Text::BibTeX Text::CSV Text::CSV_XS Text::Roman URI Unicode::Collate Unicode::GCString Unicode::LineBreak    XML::LibXML XML::LibXML::Simple XML::LibXSLT XML::Writer     autovivification File::Which Test::Differences
           ./mycpan.sh PAR PAR::Packer
           ./mycpan.sh Test::More IPC::Cmd Unicode::Normalize PerlIO::utf8_strict Storable
           #./mycpan.sh Pod::Simple::TranscodeSmart Pod::Simple::TranscodeDumb List::SomeUtils::XS List::MoreUtils::PP HTTP::Status HTTP::Date File::Find::Rule IO::Socket::SSL DateTime  Encode::
           $RUNNER_WORKSPACE/localperl/bin/perl ./Build.PL
           $RUNNER_WORKSPACE/localperl/bin/perl ./Build installdeps --cpan_client ./mycpan.sh
           $RUNNER_WORKSPACE/localperl/bin/perl ./Build test
           $RUNNER_WORKSPACE/localperl/bin/perl ./Build install
           #find $RUNNER_WORKSPACE/localperl/bin $RUNNER_WORKSPACE/localperl/lib
           sudo cp /usr/lib/x86_64-linux-gnu/libxml2.so.2 /usr/local/lib
           sudo cp /usr/lib/x86_64-linux-gnu/libz.so.1 /usr/local/lib
           sudo cp /usr/lib/x86_64-linux-gnu/libxslt.so.1 /usr/local/lib
           sudo cp /usr/lib/x86_64-linux-gnu/libexslt.so.0 /usr/local/lib
           sudo cp /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/libssl.so.0.9.8
           sudo cp /usr/lib/x86_64-linux-gnu/libcrypto.so /usr/lib/libcrypto.so.0.9.8
           sudo ln -s /usr/local/perl/lib/5.32.0/x86_64-linux /usr/local/perl/lib/5.32.0/x86_64-linux-thread-multi
           cd ./dist/linux_x86_64
           export PP_OPTS='-vvv'
           bash build.sh || true
           ./biber-linux_x86_64 --help
           unzip -o biber-linux_x86_64
           find . -name '*.so*'

       - name: Artifacts
         uses: actions/upload-artifact@v4
         with:
           name: artifacts
           path: |
             biber/dist/linux_x86_64/biber-linux_x86_64

