name: emperl

on: workflow_dispatch

env:
  URLPERL: https://www.cpan.org/src/5.0/perl-5.35.4.tar.gz
  MAKEFLAGS: -j2

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: 2.0.30

      - uses: actions/checkout@v2

      - name: Build Native Perl
        run: |
          export MAKEFLAGS
          mkdir -p source build/native/perl
          wget -nc $URLPERL -P source
          tar -xf source/$(basename $URLPERL) --strip-components=1 --directory=build/native/perl
          #mkdir ext/TeXLive
          #wget -P ext/TeXLive https://raw.githubusercontent.com/TeX-Live/installer/master/tlpkg/TeXLive/TLConfig.pm https://raw.githubusercontent.com/TeX-Live/installer/master/tlpkg/TeXLive/TLUtils.pm
          #echo > ext/TeXLive/TeXLive.pm
          pushd build/native/perl
          bash ./Configure -sde -Dman1dir=none -Dman3dir=none -Dprefix=$PWD/../prefix -Aclear:d_crypt -Aclear:d_crypt_r -Aldflags=-lm -Accflags=-lm -Dstatic_ext="IO Fcntl" -Dusedevel -Dlibs="-lpthread -lnsl -ldl -lm -lutil -lc"
          # -Uusedl
          make miniperl generate_uudmap
          make perl
          make install
          rm -rf ../prefix/man ../prefix/lib/*/pod/ || true
          find ../prefix/lib -name '*.pod' -delete
          
          find ../prefix -type f
          find -name '*.a'
          find ../prefix -name '*.so'
          #../prefix/bin/perl -MExtUtils::Embed -e ccopts -e ldopts
          #../prefix/bin/perl -MExtUtils::Embed -e xsinit -- -o xsinit.c -std Fcntl IO
          #cat xsinit.c
          
          popd

          ld -r -b binary -o fmtutil.o fmtutil.pl
          ld -r -b binary -o updmap.o  updmap.pl

          gcc -o emperl emperl.c fmtutil.o updmap.o -I$PWD/build/native/perl       -Wl,-E  -lm -fstack-protector-strong -L/usr/local/lib                         /home/runner/work/buildbiber/buildbiber/build/native/perl/../prefix/lib/5.35.4/x86_64-linux/auto/Fcntl/Fcntl.a                                      /home/runner/work/buildbiber/buildbiber/build/native/perl/../prefix/lib/5.35.4/x86_64-linux/auto/IO/IO.a                                          -L/home/runner/work/buildbiber/buildbiber/build/native/perl/../prefix/lib/5.35.4/x86_64-linux/CORE                                                  -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc -lm -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64                                                                                                                      -I/home/runner/work/buildbiber/buildbiber/build/native/perl/../prefix/lib/5.35.4/x86_64-linux/CORE
          # `../prefix/bin/perl5.35.4 -MExtUtils::Embed -e ccopts -e ldopts`

          #echo BEGIN1; ./emperl -e 'print 123; use Fcntl; print 456;'; echo END
          ldd ./emperl
          gcc preload.c -o preload.so -ldl -shared
          LD_PRELOAD=$PWD/preload.so ./emperl --help || true
          # print($^X)
          #./emperl ../../../updmap.pl --help || true
          #wget https://raw.githubusercontent.com/TeX-Live/texlive-source/trunk/texk/texlive/linked_scripts/texlive/fmtutil.pl
          #./emperl fmtutil.pl --help

#      - name: Build Wasm Perl
#        run: |
#          ROOT=$PWD
#          export MAKEFLAGS
#          mkdir -p build/wasm/perl          
#          tar -xf source/$(basename $URLPERL) --strip-components=1 --directory=build/wasm/perl
#          cd build/wasm/perl
#          emconfigure bash ./Configure -sde -Alibs=-lm -Aldflags=-lm -Accflags=-lm -Dprefix=$PWD/../prefix -Dhintfile=$PWD/../../../hintfile_wasm.sh -Dsysroot=$(dirname $(which emcc))/system -Dhostperl=$ROOT/build/native/perl/miniperl -Dhostgenerate=$ROOT/build/native/perl/generate_uudmap
#          #sed -i 's/$(generated_pods)//' Makefile
#          emmake make perl
#          emmake make install
#          rm -rf ../prefix/man ../prefix/lib/*/pod/
#          find ../prefix
#          find -name '*.a'
