name: emperl

on: workflow_dispatch

env:
  URLPERL: https://www.cpan.org/src/5.0/perl-5.30.0.tar.gz
  MAKEFLAGS: -j2

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: 2.0.30

      - uses: actions/checkout@v2

      - name: Build Native Perl
        run: |
          export MAKEFLAGS
          mkdir -p source build/native/perl
          wget -nc $URLPERL -P source
          tar -xf source/$(basename $URLPERL) --strip-components=1 --directory=build/native/perl
          cd build/native/perl
          bash ./Configure -sde -Dprefix=$PWD/../prefix -Aldflags=-lm -Accflags=-lm -Dstatic_ext="Fcntl IO"
          make miniperl generate_uudmap
          make perl
          make install
          rm -rf ../prefix/man ../prefix/lib/*/pod/
          find ../prefix
          find -name '*.a'
          # https://perldoc.perl.org/perlembed
          echo BEGIN
          ../prefix/bin/perl5.30.0 -MExtUtils::Embed -e ccopts -e ldopts
          echo END
          cc -o emperl ../../../emperl.c `../prefix/bin/perl5.30.0 -MExtUtils::Embed -e ccopts -e ldopts`
          echo BEGIN
          ./emperl -e 'print 123; use Fcntl; print 456;'
          echo END
          ldd ./emperl
          #./emperl ../../../fmtutil_.pl --help

#      - name: Build Wasm Perl
#        run: |
#          ROOT=$PWD
#          export MAKEFLAGS
#          mkdir -p build/wasm/perl          
#          tar -xf source/$(basename $URLPERL) --strip-components=1 --directory=build/wasm/perl
#          cd build/wasm/perl
#          emconfigure bash ./Configure -sde -Alibs=-lm -Aldflags=-lm -Accflags=-lm -Dprefix=$PWD/../prefix -Dhintfile=$PWD/../../../hintfile_wasm.sh -Dsysroot=$(dirname $(which emcc))/system -Dhostperl=$ROOT/build/native/perl/miniperl -Dhostgenerate=$ROOT/build/native/perl/generate_uudmap
#          #sed -i 's/$(generated_pods)//' Makefile
#          emmake make perl
#          emmake make install
#          rm -rf ../prefix/man ../prefix/lib/*/pod/
#          find ../prefix
#          find -name '*.a'
