name: staticperl_biber

env:
  URLPERL: https://www.cpan.org/src/5.0/perl-5.32.0.tar.gz
  
on: workflow_dispatch

jobs:
  staticperl_biber:
    runs-on: ubuntu-22.04
    steps:
       - name: Install Package Dependencies
         run: sudo apt install -y libxml2-dev libxslt-dev libbtparse-dev p7zip-full cmake
       
       - uses: actions/checkout@v2

       - name: Install Perl static
         run: |
           mkdir perlsourcestatic
           wget -nc $URLPERL
           tar -xf $(basename $URLPERL) --strip-components=1 --directory=perlsourcestatic
           cd perlsourcestatic
           bash +x ./Configure -sde -Dprefix="$RUNNER_WORKSPACE/localperlstatic" -Dstatic_ext="attributes B Cwd Data/Dumper Devel/Peek Digest/MD5 Digest/SHA Encode Encode/Unicode Encode/CN Encode/KR Encode/TW Encode/JP  Encode/Symbol Encode/EBCDIC Encode/Byte Fcntl File/Glob Hash/Util I18N/Langinfo IO List/Util mro Opcode PerlIO/encoding PerlIO/scalar PerlIO/via POSIX PerlIO/mmap Time/HiRes re Socket  Unicode/Normalize Unicode/Collate Compress/Raw/Zlib Compress/Raw/Bzip2 threads threads/shared Sys/Syslog Sys/Hostname File/DosGlob Math/BigInt/FastCalc Hash/Util/FieldHash Filter/Util/Call IPC/SysV MIME/Base64" -Dusedevel -Accflags="-lm -ldl" -Aldflags="-lm -ldl" -Dlibs="-lpthread -ldl -lm -lutil -lc"
           make
           make install
           $RUNNER_WORKSPACE/localperlstatic/bin/perl5.32.0 -e "print('hello world');"
           ln -s $RUNNER_WORKSPACE/localperlstatic/bin/enc2xs5.32.0 $RUNNER_WORKSPACE/localperlstatic/bin/enc2xs
           find $RUNNER_WORKSPACE/localperlstatic
           #$RUNNER_WORKSPACE/localperlstatic/bin/cpan5.32.0 -T Alien::Base::Wrapper Alien::cmake3 inc::Module::Install
           echo "$RUNNER_WORKSPACE/localperlstatic/bin" >> $GITHUB_PATH
           echo "LD_LIBRARY_PATH=$RUNNER_WORKSPACE/localperlstatic/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
       
       - name: Install build-time deps
         run: $RUNNER_WORKSPACE/localperlstatic/bin/cpan5.32.0 -T Alien::Base::Wrapper Alien::Build Alien::Build::MM Alien::cmake3 Alien::Libxml2 inc::Module::Install

       - name: Install Perl static extra packages
         run: |
           export PERLBIN=$RUNNER_WORKSPACE/localperlstatic/bin/perl5.32.0
           for MOD in Sort::Key Encode::EUCJPASCII Encode::JIS2K Encode::HanExtra XML::LibXML autovivification Devel::Caller Devel::LexAlias XML::LibXSLT XML::Parser::Expat Unicode::LineBreak Clone PadWalker  IO::Compress::Brotli PerlIO::utf8_strict HTML::Parser List::MoreUtils::XS List::SomeUtils::XS DBI Net::SSLeay Sub::Identify DateTime Storable Variable::Magic Class::XSAccessor Package::Stash::XS Params::Util; do bash build_static_perl_package.sh $MOD; done
           echo FINDPERLDIR; find $RUNNER_WORKSPACE/localperlstatic
           echo FINDEXTDIR ; find ./myext/
           zip -r myext.zip ./myext/
       
       - name: Install Perl static extra packages FAIL
         run: |
           export PERLBIN=$RUNNER_WORKSPACE/localperlstatic/bin/perl5.32.0
           set +e
           for MOD in DBD::SQLite Text::BibTeX Params::Validate::XS; do bash build_static_perl_package.sh $MOD; echo $MOD $?; done
            # PerlIO::mmap

       - name: Artifacts
         uses: actions/upload-artifact@v4
         with:
           name: artifacts
           path: myext.zip

       - name: Build Perl embedded
         run: |
           find $RUNNER_WORKSPACE/localperlstatic -name '*.a'
           gcc -o staticperl_biber staticperl_biber.c -I$PWD/perlsourcestatic -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I$RUNNER_WORKSPACE/localperlstatic/lib/5.32.0/x86_64-linux/CORE      -Wl,-E -fstack-protector-strong -fwrapv -fno-strict-aliasing -L/usr/local/lib                         $RUNNER_WORKSPACE/localperlstatic/lib/5.32.0/x86_64-linux/auto/Fcntl/Fcntl.a $RUNNER_WORKSPACE/localperlstatic/lib/5.32.0/x86_64-linux/auto/IO/IO.a $RUNNER_WORKSPACE/localperlstatic/lib/5.32.0/x86_64-linux/CORE/libperl.a -lpthread -ldl -lm -lutil -lc -lm 
           ldd staticperl_biber
           ./staticperl_biber

