name: testbiber_with_perl_packer_par

on: workflow_dispatch

# https://texdoc.org/serve/biber.pdf/0
# https://github.com/plk/biber/blob/dev/BUILDERS.README
# https://github.com/plk/biber/blob/dev/dist/linux_x86_64/build.sh
# https://github.com/plk/biber/blob/dev/dist/linux_x86_64-musl/build.sh

env:
  URLPERL: https://www.cpan.org/src/5.0/perl-5.30.0.tar.gz
  URLBIBER: https://github.com/plk/biber/archive/v2.15.tar.gz
  URLTESTPARFILES: https://master.dl.sourceforge.net/project/biblatex-biber/biblatex-biber/testfiles
  BIBERTESTPARFILES: test.bib test.bcf test-dev.bcf unifont.ttf
  PERLPLATFORM: x86_64-linux
  PERLVERSION: 5.30.0
  MAKEFLAGS: -j1
  PARLIBSSYSROOT: /usr/lib/x86_64-linux-gnu
  PARLIBSSYS: libxml2.so libz.so libxslt.so libexslt.so libssl.so.1.1 libcrypto.so.1.1
  PARLIBS: /usr/lib/libbtparse.so
  PARMODULESSYS: "deprecate Pod::Simple::TranscodeSmart Pod::Simple::TranscodeDumb List::MoreUtils::XS List::SomeUtils::XS List::MoreUtils::PP HTTP::Status HTTP::Date Encode:: File::Find::Rule IO::Socket::SSL IO::String PerlIO::utf8_strict Text::CSV_XS DateTime"
  PARMODULESBIBER: "Biber::Input::file::bibtex Biber::Input::file::biblatexml Biber::Output::dot Biber::Output::bbl Biber::Output::bblxml Biber::Output::bibtex Biber::Output::biblatexml"

jobs:
  testbiber_with_perl_packer_par:
    runs-on: ubuntu-20.04
    steps:
       - name: Install Package Dependencies
         run: sudo apt-get install -y libxml2-dev libxslt-dev libbtparse-dev

       - name: Install Perl from source
         run: |
           mkdir perl 
           wget $URLPERL
           tar -xf $(basename $URLPERL) --strip-components=1 --directory=perl

           cd perl
           #bash ./Configure -sde -Dprefix=$PWD/../prefix -Dhintfile=$PWD/../hintfile_native.sh -Dusedevel -Accflags="-lm -ldl" -Aldflags="-lm -ldl" -Dlibs="-lpthread -ldl -lm -lutil -lc"
           #bash ./Configure -sde -Dprefix=$PWD/../prefix -Dstatic_ext="attributes B Cwd Data/Dumper Devel/Peek Digest/MD5 Digest/SHA Encode Fcntl File/Glob Hash/Util I18N/Langinfo IO List/Util mro Opcode PerlIO/encoding PerlIO/scalar PerlIO/via POSIX re SDBM_File Socket Tie/Hash/NamedCapture Time/HiRes Time/Piece Unicode/Normalize                        Log/Log4perl autovivification URI Business/ISBN Business/ISSN Business/ISMN DateTime/Format/Builder DateTime/Calendar/Julian   Sort/Key Text/Roman Data/Dump Data/Compare Data/Uniqid Storable Mozilla/CA Regexp/Common Class/Accessor IO/String File/Slurper  List/Util List/AllUtils  Unicode/Collate Encode/Locale Parse/RecDescent I18N/Langinfo" -Dusedevel -Accflags="-lm -ldl" -Aldflags="-lm -ldl" -Dlibs="-lpthread -ldl -lm -lutil -lc"
           bash ./Configure -sde -Dprefix=$PWD/../prefix
           make
           make install
           ldd $PWD/../prefix/bin/perl || true
       
       - name: Install Biber Dependencies Without Test from Build.PL
         run: |
          ./prefix/bin/cpan -T Test::More Test::Differences File::Which    Module::Build    Config::AutoConf ExtUtils::LibBuilder    autovivification Class::Accessor Data::Dump Data::Compare Data::Uniqid DateTime::Format::Builder DateTime::Calendar::Julian File::Slurper IPC::Cmd IPC::Run3 List::AllUtils List::MoreUtils List::MoreUtils::XS Mozilla::CA Regexp::Common Log::Log4perl Unicode::Collate Unicode::Normalize Unicode::LineBreak Unicode::GCString Encode::Locale Encode::EUCJPASCII Encode::JIS2K Encode::HanExtra Parse::RecDescent PerlIO::utf8_strict XML::LibXML XML::LibXML::Simple XML::LibXSLT XML::Writer Sort::Key Storable Text::CSV Text::CSV_XS Text::Roman IO::String URI Text::BibTeX LWP::UserAgent LWP::Protocol::https Business::ISBN Business::ISSN Business::ISMN Lingua::Translit 
          ./prefix/bin/cpan -T PAR PAR::Packer  
       
       - name: Search PAR
         run: |
           ls 
           find ./prefix

       - name: Download and Compile Biber
         run: |
           mkdir biber
           wget $URLBIBER
           tar -xf $(basename $URLBIBER) --strip-components=1 --directory biber
           
           ROOT=$PWD
           PREFIX=$ROOT/prefix
           PARFILESBIBER="../data/biber-tool.conf;lib/Biber/biber-tool.conf ../data/schemata/config.rnc;lib/Biber/config.rnc ../data/schemata/config.rng;lib/Biber/config.rng ../data/schemata/bcf.rnc;lib/Biber/bcf.rnc ../data/schemata/bcf.rng;lib/Biber/bcf.rng ../data/bcf.xsl;Biber/bcf.xsl Biber/LaTeX/recode_data.xml;Biber/LaTeX/recode_data.xml"
           PARFILESUNICODE="$PREFIX/lib/$PERLVERSION/Unicode/Collate/Locale;lib/Unicode/Collate/Locale $PREFIX/lib/$PERLVERSION/Unicode/Collate/CJK;lib/Unicode/Collate/CJK $PREFIX/lib/$PERLVERSION/Unicode/Collate/allkeys.txt;lib/Unicode/Collate/allkeys.txt $PREFIX/lib/$PERLVERSION/Unicode/Collate/keys.txt;lib/Unicode/Collate/keys.txt"
           PARFILESSYS="$PREFIX/lib/site_perl/$PERLVERSION/Mozilla/CA/cacert.pem;lib/Mozilla/CA/cacert.pem $PREFIX/lib/$PERLVERSION/$PERLPLATFORM/PerlIO;lib/PerlIO $PREFIX/lib/$PERLVERSION/$PERLPLATFORM/auto/PerlIO;lib/auto/PerlIO $PREFIX/lib/site_perl/$PERLVERSION/Business/ISBN/RangeMessage.xml;lib/Business/ISBN/RangeMessage.xml"
           
           cd biber/lib
           PAR_VERBATIM=1 $PREFIX/bin/pp $(printf -- "--module %s " $PARMODULESSYS) $(printf -- "--module %s " $PARMODULESBIBER) $(printf -- "--link $PARLIBSSYSROOT/%s " $PARLIBSSYS) $(printf -- "--link %s " $PARLIBS) $(printf -- "--addfile %s " $PARFILESBIBER) $(printf -- "--addfile %s " $PARFILESUNICODE) $(printf -- "--addfile %s " $PARFILESSYS) --unicode --cachedeps=scancache --output=$ROOT/biber.par ../bin/biber
           ls -lah ../bin/biber
           ldd ../bin/biber || true

           # cd biber &&../prefix/bin/perl ./Build.PL
           # cd biber &&../prefix/bin/perl ./Build install

       - name: Test Biber
         run: |
           cd biber
           wget $(printf "$URLTESTPARFILES/%s " $BIBERTESTPARFILES) || true
           ../prefix/bin/perl ./Build test || true
           ../prefix/bin/perl ./bin/biber --validate-control --convert-control test || true

#ROOT=$PWD
#URLBIBER=https://github.com/plk/biber/archive/v2.15.tar.gz
#PREFIX=$ROOT/build/native/prefix
#
##mkdir -p source/biber
##wget $URLBIBER
##tar -xf $(basename $URLBIBER) --strip-components=1 --directory source/biber
#platform='x86_64-linux'
#platformsys='x86_64-linux-gnu'
#perlv='5.30.0'
#MODULESSYS="deprecate Pod::Simple::TranscodeSmart Pod::Simple::TranscodeDumb List::MoreUtils::XS List::SomeUtils::XS List::MoreUtils::PP HTTP::Status HTTP::Date Encode:: File::Find::Rule IO::Socket::SSL IO::String PerlIO::utf8_strict Text::CSV_XS DateTime"
#MODULESBIBER="Biber::Input::file::bibtex Biber::Input::file::biblatexml Biber::Output::dot Biber::Output::bbl Biber::Output::bblxml Biber::Output::bibtex Biber::Output::biblatexml"
#LIBSSYSROOT=/usr/lib/$platformsys
#LIBSSYS="libxml2.so libz.so libxslt.so libexslt.so libssl.so.1.1 libcrypto.so.1.1"
#LIBS="/usr/lib/libbtparse.so"
#FILESBIBER="../data/biber-tool.conf;lib/Biber/biber-tool.conf ../data/schemata/config.rnc;lib/Biber/config.rnc ../data/schemata/config.rng;lib/Biber/config.rng ../data/schemata/bcf.rnc;lib/Biber/bcf.rnc ../data/schemata/bcf.rng;lib/Biber/bcf.rng ../data/bcf.xsl;Biber/bcf.xsl Biber/LaTeX/recode_data.xml;Biber/LaTeX/recode_data.xml"
#FILESUNICODE="$PREFIX/lib/$perlv/Unicode/Collate/Locale;lib/Unicode/Collate/Locale $PREFIX/lib/$perlv/Unicode/Collate/CJK;lib/Unicode/Collate/CJK $PREFIX/lib/$perlv/Unicode/Collate/allkeys.txt;lib/Unicode/Collate/allkeys.txt $PREFIX/lib/$perlv/Unicode/Collate/keys.txt;lib/Unicode/Collate/keys.txt"
#FILESSYS="$PREFIX/lib/site_perl/$perlv/Mozilla/CA/cacert.pem;lib/Mozilla/CA/cacert.pem $PREFIX/lib/$perlv/$platform/PerlIO;lib/PerlIO $PREFIX/lib/$perlv/$platform/auto/PerlIO;lib/auto/PerlIO $PREFIX/lib/site_perl/$perlv/Business/ISBN/RangeMessage.xml;lib/Business/ISBN/RangeMessage.xml"
#cd source/biber/lib
##  --output=biber-linux_x86_64 \
